// Search Actions
export const FETCHING_CURRENT_GAME = 'FETCHING_CURRENT_GAME'
export const RECEIVED_CURRENT_GAME = 'RECEIVED_CURRENT_GAME'
export const ERROR_FETCHING_CURRENT_GAME = 'ERROR_FETCHING_CURRENT_GAME'

// Current Game Actions
export const RECEIVED_REALM_VERSION = 'RECEIVED_REALM_VERSION'
export const RECEIVED_CHAMPION_IMAGES = 'RECEIVED_CHAMPION_IMAGES'
export const RECEIVED_RANKED_LEAGUE = 'RECEIVED_RANKED_LEAGUE'